### ISSUE TITLE
No definition found for "/propertyPack/materialFacts/utilitiesOrServices"

### ISSUE THREAD

**Issue by jmsfwk** [Property-Data-Trust-Framework/schemas#1]

**Comment by edmolyneux** [comment]
Good spot, thanks @jmsfwk  - in the body of the schema this is broken up into waterAndDrainage and utilities (so the ordering of the original BASPI schema is the same but the number of items in each section is more balanced)

I'll update the materialFacts 'required' array to reflect that in the next commit.
