### ISSUE TITLE
Request to add MPAN to `mainsElectricity` and MPRN to `mainsGas`

### ISSUE THREAD

**Issue by KieranWitt** [Property-Data-Trust-Framework/schemas#117]
It's requested that the Meter Point Administration Number (MPAN) and Meter Point Reference Number (MPRN) be added to the schema by the property logbook working group. Energy meter numbers (MPAN/MPRN) are unique numbers that identify a property's electricity and gas supplies.

The proposal is to add these into `mainsElectricity` and `mainsGas` in `connectedUtilities`. 

Proposed addition for `mainsElectricity` 
```
"mpan": {
  "title": "Meter Point Administration Number (MPAN)",
  "description": "Your MPAN is on your electricity or dual fuel bill, usually in a box marked ‘Supply Number’. It’s 21 digits long and begins with ‘S’. You’ll only need the last 12 or 13 digits.",
  "type": "integer"
}
```

Proposed addition for `mainsGas`
```
"mprn": {
  "title": "Meter Point Reference Number (MPRN)",
  "description": "You can find your property’s MPRN on your gas or dual fuel bill. It’s usually marked ‘Meter Point Reference Number’ and is between six and 10 digits long.",
  "type": "integer"
}
```

**Comment by edmolyneux** [comment]
Great idea - can you guys create a pull request?
