### ISSUE TITLE
Enhancement to B5.1

### ISSUE THREAD

**Issue by mir491** [Property-Data-Trust-Framework/schemas#124]
current title - Are there any valid guarantees or warranties relating to this property?
proposed title - Are there any valid guarantees, warranties or indemnity insurances relating to this property?
reason - We  want to updated the title to provide a more comprehensive and inclusive wording by adding 'insurances.'"

**Comment by KieranWitt** [comment]
@mir491 Is this change intended to broaden the scope of this question from indemnity insurances to insurances?

I ask, as this creates potential duplication/confusion with Insurances in material facts.

A side effect of this change is that either
`otherGuarantees` should also be updated to "Other Guarantees, warranties or insurances". or a new object is added for `otherInsurances` (exact text being dependant on the answer to the initial question).

**Comment by mir491** [comment]
@KieranWitt As we had a discussion with ED regarding tilte of B5.1. In the code there is a different logic whereas in the pdf, there is a different logic. That is the reason why we are changing or requesting to change the question slightly. We are not making it more comprehensive or confusing rather inclusive

**Comment by mir491** [comment]
@KieranWitt my appologies, you are correct , the question title should be Are there any valid guarantees, warranties or indemnity insurances relating to this property?
