### ISSUE TITLE
Add role to verified claim vouch evidence to preserve privacy

### ISSUE THREAD

**Issue by edmolyneux** [Property-Data-Trust-Framework/schemas#165]
For many use cases we want to present that certain data items have been provenanced by vouch but for privacy reasons we don't want to disclose the name of the voucher. We should use the same roles as are available in the `participants` properties so we can at least identify that it's the seller or agent for example.

**Comment by jacknely** [comment]
@edmolyneux We want this but I'm not 100% sure if using `participant.roles` is right. 

For example, if i was a `Seller's Conveyancer`. Then Kotini would need to verify that the user is:
1) A conveyancer
2) Instructed by the seller on this transaction. 

Number 2) will be transaction specific so we wont be able to add this role to the logged in user JWT auth token. I was thinking that we go with `Conveyancer`  however then we run into a problem with `Seller` and `Buyer` as we cant add that role to token either for same reason. 

I suppose my question is, is there a solution to this that is transaction agnostic? We can use the participants array to present who is the `Seller's Conveyancer` still and then have the roles in claims as being `Conveyancer`, `Estate Agent` but what do we do for `Sellers`?
