### ISSUE TITLE
Move or copy pdtf-verified-claims.json schema to top level folder or inside latest schema version

### ISSUE THREAD

**Issue by amolpednekar** [Property-Data-Trust-Framework/schemas#186]
We use the verified claims schema [`pdtf-verified-claims.json`](https://github.com/Property-Data-Trust-Framework/schemas/blob/master/src/schemas/v1/pdtf-verified-claims.json)  to store to claims along with their verification.

This currently exists under `src/schemas/v1`, while our latest version of claims are under `src/schemas/v3`

I propose to either
* Copy `pdtf-verified-claims.json` and related tests to `/v3` folder
* Create a folder under `/schemas` and move these files there (as they are not changing - when we move to verifiable credentials, it can have its own folder. This approach ensure we don't need to copy into every `src/vN` folder

Either option will avoid confusion for new-comers trying to understand the repository and schema structure of having to still look inside v1

**Comment by edmolyneux** [comment]
Makes sense, good idea 👍 can you make sure the reference to `verifiedClaimsSchema` in `index.js` gets updated too?
