### ISSUE TITLE
Add `titleNumber` and `propertyDescription` as optional NTS fields on `ownershipsToBeTransferred`

### ISSUE THREAD

**Issue by edmolyneux** [Property-Data-Trust-Framework/schemas#234]
With multiple titles it's really hard to work out what ownership information relates to what title without pre-filling the title number and description from the deed.

With unregistered land, there's no way of manually describing what the ownership to be sold refers to.

Title number is already there as a field but is not marked with an NTS reference.

**Comment by jacknely** [comment]
@edmolyneux We use titleNumber as the unique key to update an ownership in the array with a new claim. When the title is unregistered then we have been putting “Unregistered - Freehold A” or “Unregistered - Leasehold A” etc. We had to split the ownership questions down into separate forms that get answered in different stages of the process. For example, we dont ask the managing agent details on listing but afterwards. I feel each object in this ownership array needs a unique id but if titleNumber becomes optional then what should we use?

Our implementation of the ownership claims logic still feels a bit hacky. I'm not sure what the recommended json patching strategy should be in the schema for arrays.

**Comment by edmolyneux** [comment]
Hi @jacknely it's already optional from an NTS point of view, so it's fine (and recommended) to keep requiring it in your business logic I think. Happy to jump on a call if that helps?
