### ISSUE TITLE
Question about UPRN

### ISSUE THREAD

**Issue by LFS-DMB** [Property-Data-Trust-Framework/schemas#3]
HI I see the UPRN is on the BASPI in the address section but I cannot figure out where this is stored,  I was thinking it might be with the address details but it doesn't appear to be,  could sombody explain where this is stored please.

**Comment by edmolyneux** [comment]
Hi - it's at the very top level of the schema, because it's (currently) the natural primary key we're using to identify the property.

**Comment by LFS-DMB** [comment]
Got it, cheers Ed

**Comment by edmolyneux** [comment]
By the way Darren, there are some major changes to the schema coming next week which push UPRN in alongside and nest the `propertyPack` object as part of a new top-level `pdtf-transaction` schema. We worked out that trying to key everything off OPRN wasn't going to be sustainable...

**Comment by LFS-DMB** [comment]
Hi Ed does this mean that you will no longer use UPRN as a primary key?
