### ISSUE TITLE
`ParkingArrangments` to be array instead of object?

### ISSUE THREAD

**Issue by jacknely** [Property-Data-Trust-Framework/schemas#82]
If we consider that a property can have multiple of the following:  “Garage”,  “Allocated parking space”, “Driveway”,  “On street”, “Resident permit”, “Metered parking”, and “Communal parking”, then I think either `ParkingArrangements` or `ParkingArrangementsType` needs to be an array to handle this.

For now, we will use `Other` and list selections in `otherParkingType` when there are multiple parking arrangements.

https://github.com/Property-Data-Trust-Framework/schemas/blob/600c14880bf46cdbd7247060d69857686ce4e437/src/schemas/v2/pdtf-transaction.json#L6724

**Comment by edmolyneux** [comment]
Another backwards-compatible approach might be to add a "multiple" option to the `parkingType` and then allow an array of strings in the `oneOf` clause?

**Comment by jacknely** [comment]
> Another backwards-compatible approach might be to add a "multiple" option to the parkingArrangementsType and then allow an array of strings in the oneOf clause?

@edmolyneux Let's do that. I'll get the PR raised.
