### ISSUE TITLE
Supporting the tenure being marketed

### ISSUE THREAD

**Issue by tom-at-moverly** [Property-Data-Trust-Framework/schemas#91]
Properties are typically marketed with their type of overall tenure: Freehold, Leasehold, Share of Freehold, Shared Ownership, Commonhold. The schema stores tenures for each title being sold, but the overall tenure isn't explicitly stored and has to be inferred.

Propose adding `/propertyPack/materialFacts/typeOfTenure` with enum values of 
`Freehold`
`Leasehold`
`Share of Freehold`
`Shared Ownership`
`Commonhold`

**Comment by edmolyneux** [comment]
Would it be clearer to  call this `listingTenure` or `marketingTenure`?

**Comment by tom-at-moverly** [comment]
Yes, `marketingTenure` is a more descriptive name.
